apiVersion: v1
kind: Service
metadata:
    name: keycloak-np-svc
    namespace: default
    labels:
        app: kc
spec:
    selector:
        app: kc
    type: NodePort
    ports:
        - name: kc-np-port
          protocol: TCP
          port: 30909
          nodePort: 30808
          targetPort: kc-port